version: 2
jobs:
  cypress/run:
    docker:
    - image: cypress/base:10
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Check if package-lock.json exists
        command: |
          if [ ! -e ./package-lock.json ]; then
            echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
            echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
            echo "and commit 'package-lock.json' to your repo."
            exit 1
          fi
    - run:
        name: Npm CI
        command: npm ci
    - run:
        command: npm install cypress --save-dev
    - run:
        command: npx cypress verify
    - run:
        command: ls
    - save_cache:
        key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
    - run:
        name: Run Cypress tests
        command: "ls;npx cypress run \\\n   \\\n   \\\n  "
    - store_artifacts:
        path: /root/project/cypress/videos

workflows:
  build:
    jobs:
    - cypress/run
  version: 2
