version: 2.1
  
jobs:
 build:
   # pre-built images: https://circleci.com/docs/2.0/circleci-images/
   docker:
     - image: circleci/node:10-browsers
   steps:
     - checkout
     - run:
         name: The First Step
         command: |
           npm init
           npm install cypress --save-dev
           
     - run:
         name: Code Has Arrived
         command: |
           ls -al
           echo '^^^That should look familiar^^^'
     - run:
         name: Running in a Unique Container
         command: |
           node -v
       
orbs:
  cypress: cypress-io/cypress@1

workflows:
  build:
    jobs:
      - cypress/run
